name: Report a Problem
description: File a bug report
title: "[Issue]: "
labels: ["Entomology"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: Please describe the issue in your own words
      placeholder: This is how you would see the problem again
    validations:
      required: true
  - type: textarea
    id: logcat
    attributes:
      label: Logcat Output
      description: Long press inside this box and select "Paste"
      placeholder: This is a logcat, not a secondary description
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: requirements
    attributes:
      label: Guide Confirmation
      description: By submitting this issue, you confirm checking the [guide](https://samsprung.github.io/keyboard/index.html) for SamSprung TooIME
      options:
        - label: I have reviewed the guide and included valid logcat content
          required: true
